services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    user: "root"
    ports:
      - "3000:3000"
    command: npx next dev -H 0.0.0.0
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
